Repository DeveloperAcademy-POSTECH/MC2-Team6-ECUBE, pull requests merged in 2022-06, with the labels that each got.

#1 [Feat] voicemail view & date to string VM created
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/ViewModels/DateToStringVM.swift
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
Labels: feature

#6 [Feat] Create PictureGiftView
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Assets.xcassets/Color/Contents.json
  liveOn/liveOn/Assets.xcassets/Color/background.colorset/Contents.json
  liveOn/liveOn/Assets.xcassets/Color/bodyText.colorset/Contents.json
  liveOn/liveOn/Extensions/ColorExtension.swift
  liveOn/liveOn/Helper/KeyboardHandler.swift
  liveOn/liveOn/Models/MyImage.swift
  liveOn/liveOn/Models/MyImageError.swift
  liveOn/liveOn/Models/Picker.swift
  liveOn/liveOn/System/liveOnApp.swift
  liveOn/liveOn/ViewModels/ImagePicker.swift
  liveOn/liveOn/ViewModels/ImageViewModel.swift
  liveOn/liveOn/ViewModels/ViewModel.swift
  liveOn/liveOn/Views/ContentView.swift
  liveOn/liveOn/Views/PictureGift/PictureGiftView.swift
Labels: feature

#7 [Feat] Add textLimiter & Create LetterView
  liveOn/liveOn/Assets.xcassets/Color/Contents.json
  liveOn/liveOn/Assets.xcassets/Color/background.colorset/Contents.json
  liveOn/liveOn/Assets.xcassets/Color/bodyText.colorset/Contents.json
  liveOn/liveOn/Extensions/ColorExtension.swift
  liveOn/liveOn/Helper/KeyboardHandler.swift
  liveOn/liveOn/Models/MyImage.swift
  liveOn/liveOn/Models/MyImageError.swift
  liveOn/liveOn/Models/Picker.swift
  liveOn/liveOn/ViewModels/ImagePicker.swift
  liveOn/liveOn/ViewModels/ImageViewModel.swift
  liveOn/liveOn/ViewModels/ViewModel.swift
  liveOn/liveOn/Views/ContentView.swift
  liveOn/liveOn/Views/PictureGift/PictureGiftView.swift
Labels: feature

#26 [Feat] Create FlowerView & PillView
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Views/Flower/FlowerView.swift
  liveOn/liveOn/Views/Pill/PillView.swift
Labels: feature

#35 Fix/testbranch
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Extensions/convertSecToMinAndHour.swift
  liveOn/liveOn/Models/Recording.swift
  liveOn/liveOn/ViewModels/DateToStringVM.swift
  liveOn/liveOn/ViewModels/VoiceRecorderVM.swift
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
Labels: bug, feature

#37 Origin/feature/flower
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Views/CreateGiftListView.swift
  liveOn/liveOn/Views/Flower/Flower.swift
  liveOn/liveOn/Views/Flower/FlowerListView.swift
  liveOn/liveOn/Views/Flower/FlowerView.swift
  liveOn/liveOn/Views/Pill/Pill.swift
  liveOn/liveOn/Views/Pill/PillListView.swift
  liveOn/liveOn/Views/Pill/PillView.swift
Labels: feature

#41 [Feat] Voicemail View Completed & [Refactor] Voicemail View Refactored
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Models/Recording.swift
  liveOn/liveOn/ViewModels/DateToStringVM.swift
  liveOn/liveOn/ViewModels/VoiceRecorderVM.swift
  liveOn/liveOn/Views/CreateGiftListView.swift
  liveOn/liveOn/Views/Voicemail/VoicemailMainView.swift
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
Labels: feature

#46 Enhance PillView & FlowerView
  liveOn/liveOn/Views/Flower/FlowerListView.swift
  liveOn/liveOn/Views/Flower/FlowerView.swift
  liveOn/liveOn/Views/Pill/PillView.swift
Labels: enhancement

#51 [Feat] Create Flower PopUp Window + etc
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Views/CreateGiftListView.swift
  liveOn/liveOn/Views/Flower/FlowerDetailView.swift
  liveOn/liveOn/Views/GiftBoxView.swift
Labels: feature

#53 [Feat] Create Flower PopUp Window + etc
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/ViewModels/imageViewModel.swift
  liveOn/liveOn/Views/ContentView.swift
  liveOn/liveOn/Views/CreateGiftListView.swift
  liveOn/liveOn/Views/GiftBoxView.swift
  liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift
  liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift
  liveOn/liveOn/Views/SignIn/SelectWhatToDoView.swift
Labels: feature

#61 [Fix] Enhance FlowerListView + etc
  liveOn/liveOn/Views/Flower/FlowerListView.swift
  liveOn/liveOn/Views/Flower/FlowerView.swift
Labels: feature

#67 [Feat] Server Communication added (Voicemail, Get fin.)
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Etc/NetworkLoggerPlugin.swift
  liveOn/liveOn/Models/ServerCommunication.swift
  liveOn/liveOn/ViewModels/ServerCommunicationVM.swift
  liveOn/liveOn/ViewModels/VoiceRecorderVM.swift
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
Labels: feature

#109 [Enhancement] 초대코드 공유 및 입력 플로우 추가 & 첫화면 수정(GettingStartView)
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  liveOn/liveOn/Assets.xcassets/AccentColor.colorset/Contents.json
  liveOn/liveOn/Assets.xcassets/successMatching.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/successMatching.imageset/successMatching.png
  liveOn/liveOn/Extensions/BackButtonExtension.swift
  liveOn/liveOn/Views/ContentView.swift
  liveOn/liveOn/Views/PictureGift/PhotoTransport.swift
  liveOn/liveOn/Views/SignIn/EnterCodeView.swift
  liveOn/liveOn/Views/SignIn/GettingStartView.swift
  liveOn/liveOn/Views/SignIn/SelectWhatToDoView.swift
  liveOn/liveOn/Views/SignIn/ShareSheet.swift
  liveOn/liveOn/Views/SignIn/User.swift
  liveOn/liveOn/Views/SignIn/WelcomMatchingView.swift
Labels: enhancement, feature, refactor

#105 [Fix] Replace app icon with new one + etc
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/AppIcon_ver_05.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/AppIcon_ver_05_120px.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/AppIcon_ver_05_152px.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/AppIcon_ver_05_167px.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/AppIcon_ver_05_180px.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/AppIcon_ver_05_76px.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/Contents.json
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  liveOn/liveOn/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  liveOn/liveOn/Assets.xcassets/photo_aquarium.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/photo_aquarium.imageset/photo_aquarium.jpg
  liveOn/liveOn/Assets.xcassets/photo_book.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/photo_book.imageset/photo_book.jpg
  liveOn/liveOn/Assets.xcassets/photo_picnic.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/photo_picnic.imageset/photo_picnic.jpg
  liveOn/liveOn/Assets.xcassets/photo_sky.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/photo_sky.imageset/photo_sky.jpg
  liveOn/liveOn/Assets.xcassets/photo_wedding.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/photo_wedding.imageset/photo_wedding.jpg
  liveOn/liveOn/Network/Service/AuthNetworkService.swift
  liveOn/liveOn/ViewModels/AuthenticationViewModel.swift
  liveOn/liveOn/Views/Letter/Letter.swift
  liveOn/liveOn/Views/PictureGift/Photo.swift
  liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift
  liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift
  liveOn/liveOn/Views/SignIn/GettingStartView.swift
  liveOn/liveOn/Views/SignIn/SelectWhatToDoView.swift
  liveOn/liveOn/Views/SignIn/SetBirthdayView.swift
  liveOn/liveOn/Views/SignIn/SetFirstDayView.swift
  liveOn/liveOn/Views/SignIn/SetNicknameView.swift
Labels: enhancement, feature

#108 [Feat] Playing recordings from server completed & refactor VoicemailsView
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Assets.xcassets/Colors/CassetteBorder.colorset/Contents.json
  liveOn/liveOn/Assets.xcassets/Colors/Grey.colorset/Contents.json
  liveOn/liveOn/Assets.xcassets/cassetteLabel1.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/cassetteLabel1.imageset/flower1.png
  liveOn/liveOn/Assets.xcassets/cassetteLabel2.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/cassetteLabel2.imageset/flower2.png
  liveOn/liveOn/Assets.xcassets/cassetteLabel3.imageset/Contents.json
  liveOn/liveOn/Assets.xcassets/cassetteLabel3.imageset/flower.png
  liveOn/liveOn/Models/Recording.swift
  liveOn/liveOn/Models/ServerCommunication.swift
  liveOn/liveOn/Models/UserVoiceMail.swift
  liveOn/liveOn/ViewModels/ServerCommunicationViewModel.swift
  liveOn/liveOn/ViewModels/VoiceRecorderViewModel.swift
  liveOn/liveOn/ViewModels/VoicemailPlayerViewModel.swift
  liveOn/liveOn/Views/Voicemail/VoicemailCassette.swift
  liveOn/liveOn/Views/Voicemail/VoicemailPopUpView.swift
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
  liveOn/liveOn/Views/Voicemail/VoicemailsView.swift
Labels: feature, refactor

#113 [Refactor] PictureListView refactored
  liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift
Labels: refactor

#116 [Refactor] Refactor PhotoCard Create & List | Swipe 뒤로가기 구현
  liveOn/liveOn.xcodeproj/project.pbxproj
  liveOn/liveOn/Extensions/NavigationControllerExtension.swift
  liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift
  liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift
  liveOn/liveOn/Views/Pill/PillListView.swift
Labels: enhancement

#121 [Refactor] overall refactoring
  liveOn/liveOn/Models/ServerCommunication.swift
  liveOn/liveOn/ViewModels/VoiceRecorderViewModel.swift
  liveOn/liveOn/Views/CreateGiftListView.swift
  liveOn/liveOn/Views/GiftBoxView.swift
  liveOn/liveOn/Views/Letter/CreateLetterView.swift
  liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift
  liveOn/liveOn/Views/PictureGift/PhotoTransport.swift
  liveOn/liveOn/Views/Pill/PillView.swift
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
  liveOn/liveOn/Views/Voicemail/VoicemailsView.swift
Labels: refactor

#124 [Refactor] refactored for test presentation
  liveOn/liveOn/Views/Voicemail/VoicemailView.swift
Labels: refactor
